<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Course Categories' => '',
    'Create' => '保存',
    'Delete' => '',
    'ID' => '',
    'Update' => '保存',
    'Update {modelClass}: ' => '',
    '价格' => '',
    '优惠价格' => '',
    '保存' => '',
    '分享次数' => '',
    '分类描述' => '',
    '列表图片' => '',
    '名称' => '',
    '在学人数' => '',
    '封面图片' => '',
    '授课教师' => '',
    '收藏次数' => '',
    '新建课程' => '',
    '新建课程分类' => '',
    '是否可用' => '',
    '查询' => '',
    '浏览次数' => '',
    '父级分类' => '',
    '班主任' => '',
    '编辑课程' => '',
    '课程分类' => '',
    '课程分类列表' => '',
    '课程分类名称' => '',
    '课程列表' => '',
    '课程创建时间' => '',
    '课程详情' => '',
    '重置' => '',
];
