<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Course Categories' => '',
    'Create' => '保存',
    'Delete' => '删除',
    'ID' => '',
    'Update' => '修改',
    'Search' => '查询',
    'Reset' => '重置',
    'Update {modelClass}: ' => '',
    'Courses' => '课程列表',
    'Create Course' => '新建课程',
    'Course Categories' => '课程分类列表',
    'Course Packages' => '套餐列表',
    'Create Course Package' => '新建套餐',
    'Course Package Categories' => '套餐分类列表',
    'Create Course Package Category' => '新建套餐分类',
    'Create Course Category' => '新建课程分类',
    'Course Chapters' => '课程章节',
    'Create Course Chapter' => '新建章',
    'Create Section Chapter' => '新建节',
    '价格' => '',
    '优惠价格' => '',
    '保存' => '',
    '分享次数' => '',
    '分类描述' => '',
    '列表图片' => '',
    '名称' => '',
    '在学人数' => '',
    '封面图片' => '',
    '授课教师' => '',
    '收藏次数' => '',
    '新建课程' => '',
    '新建课程分类' => '',
    '是否可用' => '',
    '查询' => '',
    '浏览次数' => '',
    '父级分类' => '',
    '班主任' => '',
    '编辑课程' => '',
    '课程分类' => '',
    '课程分类列表' => '',
    '课程分类名称' => '',
    '课程列表' => '',
    '课程创建时间' => '',
    '课程详情' => '',
    '重置' => '',
    'Hot Categories' => '热门分类',
    'Create Hot Category' => '创建热门分类',
    'Course News' => '新闻列表',
    'Create Course News' => '新建新闻',
    'Friendly Links' => '友情链接',
    'Course Coments' => '课程评价',
    'Create Course Coment' => '新建课程评价',
    'Datas' => '资料列表',
    'Create Data' => '创建资料',
    'Collections' => '收藏列表',
    'Quas' => '教师答疑',
    'Create Quas' => '回答问题',
    'Create User' => '创建用户',
    'Users' => '用户列表',
    'Order Infos' => '订单列表',
    'Create Order Info' => '创建订单',
    'Update Order Info' => '修改订单',
    'Marketers' => '市场专员列表',
    'Cards' => '充值卡列表',
    'Comments' => '学习感言',
    'Create Comment' => '创建学习感言'
];
