<?php

namespace api\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use backend\models\Course;
use backend\models\CourseCategory;
use backend\models\User;
use backend\models\CourseChapter;
use backend\models\CourseSection;
use backend\models\CourseComent;
use backend\models\Data;
use backend\models\Quas;
use backend\models\UserStudyLog;
use Qiniu\Auth;
use yii\data\Pagination;

/**
 * AudioController implements the CRUD actions for Audio model.
 */
class CourseController extends Controller
{
    public function init() {
        header("Origin:http://localhost:8080");
        header("Access-Control-Allow-Origin:http://localhost:8080");
        header("Access-Control-Request-Headers:http://localhost:8080");
        header("Access-Control-Allow-Credentials:true");
        header("Access-Control-Allow-Headers: Content-Type, X-Requested-With, Cache-Control,Authorization");
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function actionList()
    {
        $courses = Course::find()
        ->where(['type' => 1])
        ->with([
            'courseChapters' => function($query) {
                $query->with(['courseSections' => function($query) {
                    $query->with('courseSectionPoints');
                }]);
            }
        ])
        ->orderBy('create_time desc')
        ->all();
        $result = array();
        foreach ($courses as $key => $course) {
            $id_arr = explode(',', $course->teacher_id);
            $teacher_name = '';
            foreach ($id_arr as $key => $id) {
                $teacher = User::getUserModel($id);
                if ($teacher) {
                    $teacher_name = $teacher->username.','.$teacher_name;
                }
            }
            // 去除最后一个逗号
            $teacher_name = substr($teacher_name, 0, strlen($teacher_name)-1);
            $classrooms = 0;
            $chapters = $course->courseChapters;
            foreach ($chapters as $key => $chapter) {
                $sections = $chapter->courseSections;
                foreach ($sections as $key => $section) {
                    $points = $section->courseSectionPoints;
                    $classrooms += count($points);
                }
            }
            $content = array(
                'id' => $course->id,
                'course_name' => $course->course_name,
                'list_pic' => $course->list_pic,
                'discount' => $course->discount,
                'online' => $course->online,
                'teacher' => $teacher_name,
                'classrooms' => $classrooms
            );
            $result[] = $content;
        }
        return json_encode($result);
    }
    public function actionDetail()
    {
        $data = Yii::$app->request->get();
        $access_token = '';
        if (!empty($data['access-token'])) {
            $access_token = $data['access-token'];
        }
        $user = \common\models\User::findIdentityByAccessToken($access_token);
        $courseid = $data['courseid'];
        $invite = 0;
        if (isset($data['invite'])) {
            $invite = $data['invite'];
        }
        //设置邀请人cookie
        $cookies = Yii::$app->response->cookies;
        if (!isset($cookies['invite']) && ($invite > 0)) {
            $cookies->add(new \yii\web\Cookie([
                'name' => 'invite',
                'value' => $invite,
                'expire'=>time()+3600*24*365
            ]));
        }
        $courseModel = Course::find()
        ->where(['id' => $courseid])
        ->with([
            'courseChapters' => function($query) {
                $query->with(['courseSections' => function($query) {
                    $query->with('courseSectionPoints');
                }]);
            }
        ])
        ->one();
        //浏览次数加1
        $courseModel->view = $courseModel->view+1;
        $courseModel->save();
        $courseDetail = array();
        /* 课程详情 */
        $ismember = 0;
        $ispay = 0;
        $isschool = 0;
        if (!empty($user)) {
            $roles_array = Yii::$app->authManager->getRolesByUser($user->id);
            if (array_key_exists('school',$roles_array)) {
                $isschool = 1;
            }
            $ismember = Course::ismember($courseModel->id, $user->id);
            $ispay = Course::ispay($courseModel->id, $user->id);
        }
        if ($courseModel->discount == 0) {
            $tag = 1; //公开课程
        } else if ($ismember == 1) {
            $tag = 2; //会员课程
        } else if ($ispay == 1 || $isschool == 1) {
            $tag = 3; //已购买课程
        } else {
            $tag = 0; //尚未购买
        }
        $course = array(
            'id' => $courseModel->id,
            'course_name' => $courseModel->course_name,
            'discount' => $courseModel->discount,
            'price' => $courseModel->price,
            'home_pic' => $courseModel->home_pic,
            'teacher' => User::item($courseModel->teacher_id),
            'class' => $duration/60,
            'view' => $courseModel->view,
            'collection' => $courseModel->collection,
            'online' => $courseModel->online,
            'intro' => $courseModel->des,
            'ispay' => $tag,
            'course_type' => $courseModel->type
        );
        $courseDetail['course'] = $course;
        //课程教师
        $teacher_model = User::getUserModel($courseModel->teacher_id);
        $teacher = array(
            'teacher_img' => Url::to('@web'.$teacher_model->picture, true),
            'teacher_name' => $teacher_model->username,
            'teacher_tag' => $teacher_model->description,
            'office' => $teacher_model->office,
            'unit' => $teacher_model->unit,
            'goodat' => $teacher_model->goodat
        );
        $courseDetail['teacher'] = $teacher;
        /* 获取前12个学员 */
        $studyids = UserStudyLog::find()
        ->select('userid')
        ->where(['courseid' => $courseid])
        ->orderBy('start_time desc')
        ->limit(12)
        ->asArray()
        ->all();
        if (!empty($studyids)) {
            $studyids = array_column($studyids, 'userid');
            $studyids = array_unique($studyids);
            foreach ($studyids as $key => $studyid) {
                $content = array(
                    'student_img' => Url::to('@web'.User::getUserModel($studyid)->picture, true),
                    'student_name' => User::item($studyid)
                );
                $courseDetail['students'][] = $content;
            }
        }
        return  json_encode($courseDetail);
    }
    public static function getVideoType($section)
    {
        $text = '';
        $current_time = date('Y-m-d H:i:s');
        $end_time = date('Y-m-d H:i:s',strtotime($section->start_time."+".$section->duration." minute"));
        //0 直播 2 直播答疑
        $video_url = $section->video_url;
        if ($section->type == 0 || $section->type == 2) {
            if ($current_time < $section->start_time) {
                $text = '最近直播：'.$section->start_time;
            } else if ($current_time >= $section->start_time && $current_time < $end_time) {
                 $text = '直播中';
            } else if ($current_time > $end_time) {
                $text = '直播回放';
            }
        } else if ($section->type == 1) {
            $text = '点播课程';
        }
        $url = '';
        if ($section->type == 0 || $section->type == 2) {
            $url = $section->video_url;
        }
        $result = array(
            'text' => $text,
            'url' => $url
        );
        return $result;
    }
    public function actionCheck()
    {
        $get = Yii::$app->request->get();
        $access_token = $get['access-token'];
        $user = \common\models\User::findIdentityByAccessToken($access_token);
        if (empty($user)) {
            $result = array(
                'status' => 0,
                'message' => '请先登陆再观看课程'
            );
            return json_encode($result);
        }
        $data = Yii::$app->request->post();
        $section_id = $data['section_id'];
        $course_id = $data['course_id'];
        $section = CourseSection::find()
        ->where(['id' => $section_id])
        ->one();
        if (!empty($section)) {
            if ($section->paid_free == 0) {
                $result = array(
                    'status' => 1,
                    'message' => '正在请求观看免费课程',
                    'url' => $section->video_url
                );
                return json_encode($result);
            } else {
                $auth = new Auth(Yii::$app->params['access_key'], Yii::$app->params['secret_key']);
                $video_url = $auth->privateDownloadUrl($section->video_url, $expires = 3600);
                $is_member = Course::ismember($course_id, $user->id);/*判断是否是该分类下的会员*/
                if ($is_member == 1) {
                    $result = array(
                        'status' => 4,
                        'message' => '会员，允许观看',
                        'url' => $video_url
                    );
                    return json_encode($result);
                }
                $ispay = Course::ispay($course_id, $user->id);/*判断是否已经购买*/
                $roles_array = Yii::$app->authManager->getRolesByUser($user->id);
                $isschool = 0;
                if (array_key_exists('school',$roles_array)) {
                    $isschool = 1;
                }
                if ($ispay == 1 || $isschool == 1) {
                    $result = array(
                        'status' => 2,
                        'message' => '用户已经购买了该课程，允许观看',
                        'url' => $video_url
                    );
                } else {
                    $result = array(
                        'status' => 3,
                        'message' => '您尚未购买该课程，请先购买后再观看',
                        'url' => ''
                    );
                }
                return json_encode($result);
            }
        }
    }
    public function actionNodes() {
        $get = Yii::$app->request->get();
        $pageSize = $get['pernumber'];
        $page = $get['page'];
        $courseChapter = CourseChapter::find()
        ->all();
        $course_nodes = CourseCategory::find()
        ->select('id, name')
        ->where(['not like', 'name', '公开课'])
        ->with([
            'courses' => function ($query){
                $query->select('id, course_name, category_name')
                ->where(['type' => 1])
                ->with(['courseChapters' => function ($query) {
                    $query->select('id, name, course_id');
                }]);
            }
        ]);
        //实例化分页类,带上参数(总条数,每页显示条数)
        $pages = new Pagination(['totalCount' =>$course_nodes->count(), 'pageSize' => $pageSize]);
        $models = $course_nodes->offset($pages->offset)->limit($pages->limit)
        ->all();
        $datas = array();
        foreach ($models as $key => $model) {
            foreach ($model->courses as $key => $course) {
                foreach ($course->courseChapters as $key => $chapter) {
                    $data = array();
                    $data['subid'] = $model->id;
                    $data['subname'] = $model->name;
                    $data['courseid'] = $course->id;
                    $data['coursename'] = $course->course_name;
                    $data['sectionid'] = $chapter->id;
                    $data['name'] = $chapter->name;
                    $datas[] = $data;
                }
            }
        }
        $result = array(
            'data' => $datas,
            'sectionsCount' => count($courseChapter)
        );
        return json_encode($result);
    }
    public function actionAllNodes() {
        $course_nodes = CourseCategory::find()
        ->select('id, name')
        ->where(['not like', 'name', '公开课'])
        ->with([
            'courses' => function ($query){
                $query->select('id, course_name, category_name')
                ->where(['type' => 1])
                ->with(['courseChapters' => function ($query) {
                    $query->select('id, name, course_id');
                }]);
            }
        ])
        ->asArray()
        ->all();
        return json_encode($course_nodes);
    }

    public function actionOpen() {
        $courses = Course::find()
        ->where(['onuse' => 1])
        ->andWhere(['type' => 2])
        ->orderBy('create_time desc')
        ->all();
        $result = array();
        foreach ($courses as $key => $course) {
            $content = array(
                'id' => $course->id,
                'course_name' => $course->course_name,
                'list_pic' => $course->list_pic,
                'intro' => $course->intro,
                'duration' => $course->duration
            );
            $result[] = $content;
        }
        return json_encode($result);
    }

    public function actionOpenCheck() {
        try {
            $post = Yii::$app->request->post();
            $access_token = $post['access-token'];
            $user = \common\models\User::findIdentityByAccessToken($access_token);
        } catch (Exception $e) {
            echo 'Caught exception: ',  $e->getMessage(), "\n";
        } finally {
            if (empty($user)) {
                $result = array(
                    'status' => 0,
                    'message' => '请先登陆再观看课程',
                );
                return json_encode($result);
            }
            $course_id = $post['course_id'];
            $course = Course::find()
            ->where(['id' => $course_id])
            ->one();
            if($course->price == 0) {
                $result = array(
                    'status' => 4,
                    'message' => '该课程免费，可以直接观看',
                    'url' => $course->open_course_url
                );
                return json_encode($result);
            }
            $ispay = Course::ispay($course_id, $user->id);/*判断是否已经购买,84应该为$user->id*/
            $roles_array = Yii::$app->authManager->getRolesByUser($user->id);//84应该为$user->id
            $isschool = 0;
            if (array_key_exists('school',$roles_array)) {
                $isschool = 1;
            }
            if ($ispay == 1 || $isschool == 1) {
                $result = array(
                    'status' => 2,
                    'message' => '用户已经购买了该课程，允许观看',
                    'url' => $course->open_course_url
                );
            } else {
                $result = array(
                    'status' => 3,
                    'message' => '您尚未购买该课程，请先购买后再观看',
                    'url' => '',
                    'courseid' => $course->price
                );
            }
            return json_encode($result);
        }
    }
}
